services:
  postgres:
    image: postgres:16-alpine
    container_name: redember-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: redember
    volumes:
      - redember_pgdata:/var/lib/postgresql/data

volumes:
  redember_pgdata:
